Adds Copy assets to dist
WomenWhoCode/frontend-fridays pull request #4
Opened 2022-12-14 13:03 UTC by luzaracelydls

2022-12-14 13:12 UTC, mharizanova8703 approved these changes

2022-12-14 14:56 UTC, mharizanova8703 approved these changes

2022-12-16 15:18 UTC, poulami-saha approved these changes

2022-12-16 16:13 UTC, mharizanova8703 requested changes
looks great

2022-12-16 16:13 UTC, mharizanova8703 commented
looks great

2022-12-16 16:15 UTC, mharizanova8703 requested changes
thank you. work as expected

2023-01-08 22:22 UTC, closed without merging